apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        # IMPORTANT: The Jenkinsfile will replace 'placeholder' with the correct image tag.
        image: placeholder
        ports:
        - containerPort: 3001
